"use client";

import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import {
  X,
  Check,
  AlertCircle,
  Loader2,
  ExternalLink,
  LogOut,
  Lock,
  Globe,
  GitBranch,
} from "lucide-react";

function GithubIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
    </svg>
  );
}

import { cn } from "@/lib/utils";
import type { ProjectFile } from "@/lib/types";

interface GithubUser {
  connected: boolean;
  login?: string;
  name?: string | null;
  avatar_url?: string;
}

interface Props {
  projectName: string;
  files: ProjectFile[];
  onClose: () => void;
}

export function GithubModal({ projectName, files, onClose }: Props) {
  const [user, setUser] = useState<GithubUser | null>(null);
  const [loadingUser, setLoadingUser] = useState(true);
  const [repoName, setRepoName] = useState(
    projectName.toLowerCase().replace(/[^a-z0-9._-]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "") || "gostera-project"
  );
  const [isPrivate, setIsPrivate] = useState(false);
  const [commitMessage, setCommitMessage] = useState("Generated by Gostera AI");
  const [pushing, setPushing] = useState(false);
  const [result, setResult] = useState<{ repoUrl: string; commitSha: string; filesCount: number } | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchUser = useCallback(async () => {
    setLoadingUser(true);
    try {
      const res = await fetch("/api/github/user");
      const data = await res.json() as GithubUser;
      setUser(data);
    } catch {
      setUser({ connected: false });
    } finally {
      setLoadingUser(false);
    }
  }, []);

  useEffect(() => {
    fetchUser();
  }, [fetchUser]);

  const handleConnect = () => {
    window.location.href = "/api/github/auth";
  };

  const handleDisconnect = async () => {
    await fetch("/api/github/disconnect", { method: "DELETE" });
    setUser({ connected: false });
    setResult(null);
    setError(null);
  };

  const handlePush = async () => {
    if (!files.length) return;
    setPushing(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch("/api/github/push", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoName, isPrivate, files, commitMessage }),
      });

      const data = await res.json() as {
        success?: boolean;
        repoUrl?: string;
        commitSha?: string;
        filesCount?: number;
        error?: string;
      };

      if (!res.ok || !data.success) {
        setError(data.error ?? "Push failed. Please try again.");
      } else {
        setResult({
          repoUrl: data.repoUrl!,
          commitSha: data.commitSha!,
          filesCount: data.filesCount!,
        });
      }
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setPushing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div className="bg-card border border-border rounded-xl shadow-2xl w-full max-w-md mx-4 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border">
          <div className="flex items-center gap-2">
            <GithubIcon className="h-4 w-4 text-foreground" />
            <h2 className="text-sm font-semibold">Push to GitHub</h2>
          </div>
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </div>

        <div className="p-4 space-y-4">
          {/* Auth state */}
          {loadingUser ? (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              Checking GitHub connection…
            </div>
          ) : !user?.connected ? (
            /* Not connected */
            <div className="space-y-3">
              <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/40 border border-border/60">
                <GithubIcon className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
                <div>
                  <p className="text-sm font-medium">Connect your GitHub account</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Authorize Gostera to create and push to repositories on your behalf.
                  </p>
                </div>
              </div>
              <Button className="w-full gap-2" onClick={handleConnect}>
                <GithubIcon className="h-4 w-4" />
                Connect GitHub
              </Button>
            </div>
          ) : result ? (
            /* Success state */
            <div className="space-y-3">
              <div className="flex items-start gap-3 p-3 rounded-lg bg-green-500/10 border border-green-500/30">
                <Check className="h-5 w-5 text-green-500 mt-0.5 shrink-0" />
                <div>
                  <p className="text-sm font-semibold text-green-400">Pushed successfully!</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {result.filesCount} files committed to{" "}
                    <span className="font-mono text-foreground">{repoName}</span>
                  </p>
                  <p className="text-[10px] font-mono text-muted-foreground/60 mt-1">
                    {result.commitSha.slice(0, 7)}
                  </p>
                </div>
              </div>
              <a
                href={result.repoUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center gap-2 w-full h-9 rounded-lg border border-border text-sm font-medium hover:bg-accent/50 transition-colors"
              >
                <ExternalLink className="h-4 w-4" />
                View on GitHub
              </a>
              <Button variant="outline" className="w-full" onClick={() => setResult(null)}>
                Push again
              </Button>
            </div>
          ) : (
            /* Push form */
            <div className="space-y-3">
              {/* Connected as */}
              <div className="flex items-center justify-between p-2.5 rounded-lg bg-muted/40 border border-border/60">
                <div className="flex items-center gap-2">
                  {user.avatar_url && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={user.avatar_url} alt={user.login} className="w-6 h-6 rounded-full" />
                  )}
                  <div>
                    <p className="text-xs font-medium text-foreground">{user.name ?? user.login}</p>
                    <p className="text-[10px] text-muted-foreground">@{user.login}</p>
                  </div>
                </div>
                <button
                  onClick={handleDisconnect}
                  className="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-destructive transition-colors"
                >
                  <LogOut className="h-3 w-3" /> Disconnect
                </button>
              </div>

              {/* Repo name */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  Repository name
                </label>
                <div className="flex items-center gap-1.5 bg-background border border-border rounded-lg px-3 py-2">
                  <GitBranch className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                  <input
                    value={repoName}
                    onChange={(e) =>
                      setRepoName(
                        e.target.value
                          .toLowerCase()
                          .replace(/[^a-z0-9._-]/g, "-")
                          .replace(/-+/g, "-")
                      )
                    }
                    placeholder="my-app"
                    className="flex-1 text-sm bg-transparent outline-none text-foreground"
                  />
                </div>
                <p className="text-[10px] text-muted-foreground">
                  Will be created at github.com/{user.login}/{repoName || "…"}
                </p>
              </div>

              {/* Commit message */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  Commit message
                </label>
                <input
                  value={commitMessage}
                  onChange={(e) => setCommitMessage(e.target.value)}
                  placeholder="Initial commit"
                  className="w-full text-sm bg-background border border-border rounded-lg px-3 py-2 outline-none focus:ring-1 focus:ring-primary text-foreground"
                />
              </div>

              {/* Visibility toggle */}
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setIsPrivate(false)}
                  className={cn(
                    "flex-1 flex items-center justify-center gap-2 py-2 rounded-lg border text-xs font-medium transition-colors",
                    !isPrivate
                      ? "border-primary bg-primary/10 text-primary"
                      : "border-border text-muted-foreground hover:bg-accent/50"
                  )}
                >
                  <Globe className="h-3.5 w-3.5" /> Public
                </button>
                <button
                  onClick={() => setIsPrivate(true)}
                  className={cn(
                    "flex-1 flex items-center justify-center gap-2 py-2 rounded-lg border text-xs font-medium transition-colors",
                    isPrivate
                      ? "border-primary bg-primary/10 text-primary"
                      : "border-border text-muted-foreground hover:bg-accent/50"
                  )}
                >
                  <Lock className="h-3.5 w-3.5" /> Private
                </button>
              </div>

              {/* File count info */}
              <p className="text-[11px] text-muted-foreground text-center">
                {files.length} file{files.length !== 1 ? "s" : ""} will be pushed in a single commit
              </p>

              {/* Error */}
              {error && (
                <div className="flex items-start gap-2 p-2.5 rounded-lg bg-destructive/10 border border-destructive/30">
                  <AlertCircle className="h-4 w-4 text-destructive shrink-0 mt-0.5" />
                  <p className="text-xs text-destructive">{error}</p>
                </div>
              )}

              {/* Push button */}
              <Button
                className="w-full gap-2"
                onClick={handlePush}
                disabled={pushing || !repoName || !files.length}
              >
                {pushing ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Pushing {files.length} files…
                  </>
                ) : (
                  <>
                    <GithubIcon className="h-4 w-4" />
                    Push to GitHub
                  </>
                )}
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
