import { NextRequest, NextResponse } from "next/server";

const GITHUB_COOKIE = "gh_token";

type GHFile = { path: string; content: string };

async function ghFetch(token: string, path: string, options: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
  return res;
}

export async function POST(req: NextRequest) {
  const token = req.cookies.get(GITHUB_COOKIE)?.value;
  if (!token) {
    return NextResponse.json({ error: "Not connected to GitHub" }, { status: 401 });
  }

  let body: { repoName: string; isPrivate: boolean; files: GHFile[]; commitMessage?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const { repoName, isPrivate, files, commitMessage = "Generated by Gostera AI" } = body;

  if (!repoName || !files?.length) {
    return NextResponse.json({ error: "Missing repoName or files" }, { status: 400 });
  }

  // Sanitize repo name: lowercase, replace spaces/special chars with hyphens
  const sanitizedName = repoName
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 100) || "gostera-project";

  // 1. Get authenticated user login
  const userRes = await ghFetch(token, "/user");
  if (!userRes.ok) {
    return NextResponse.json({ error: "Failed to get GitHub user" }, { status: 500 });
  }
  const user = await userRes.json() as { login: string };
  const owner = user.login;

  // 2. Check if repo exists, create if not
  const repoCheckRes = await ghFetch(token, `/repos/${owner}/${sanitizedName}`);
  let defaultBranch = "main";
  let repoUrl = `https://github.com/${owner}/${sanitizedName}`;

  if (repoCheckRes.status === 404) {
    // Create new repo
    const createRes = await ghFetch(token, "/user/repos", {
      method: "POST",
      body: JSON.stringify({
        name: sanitizedName,
        private: isPrivate,
        auto_init: false,
        description: `Generated by Gostera AI`,
      }),
    });
    if (!createRes.ok) {
      const err = await createRes.json() as { message?: string };
      return NextResponse.json({ error: err.message ?? "Failed to create repo" }, { status: 500 });
    }
    const repo = await createRes.json() as { default_branch: string; html_url: string };
    defaultBranch = repo.default_branch ?? "main";
    repoUrl = repo.html_url;
  } else if (repoCheckRes.ok) {
    const repo = await repoCheckRes.json() as { default_branch: string; html_url: string };
    defaultBranch = repo.default_branch ?? "main";
    repoUrl = repo.html_url;
  } else {
    return NextResponse.json({ error: "Failed to check repo" }, { status: 500 });
  }

  // 3. Get current HEAD commit SHA (if the repo has commits). We deliberately
  // do NOT reuse its tree as a base_tree: Gostera sends the project's *complete*
  // file set every push, so building the tree from scratch makes the commit a
  // true snapshot — files deleted in Gostera disappear from the repo instead of
  // lingering forever. (F7b)
  let parentSha: string | null = null;

  const refRes = await ghFetch(token, `/repos/${owner}/${sanitizedName}/git/ref/heads/${defaultBranch}`);
  if (refRes.ok) {
    const ref = await refRes.json() as { object: { sha: string } };
    parentSha = ref.object.sha;
  }

  // 4. Create blobs for all files (in parallel batches of 5 to avoid rate limits)
  const blobShas: { path: string; sha: string }[] = [];

  for (let i = 0; i < files.length; i += 5) {
    const batch = files.slice(i, i + 5);
    const results = await Promise.all(
      batch.map(async (file) => {
        const blobRes = await ghFetch(
          token,
          `/repos/${owner}/${sanitizedName}/git/blobs`,
          {
            method: "POST",
            body: JSON.stringify({
              content: Buffer.from(file.content).toString("base64"),
              encoding: "base64",
            }),
          }
        );
        if (!blobRes.ok) throw new Error(`Failed to create blob for ${file.path}`);
        const blob = await blobRes.json() as { sha: string };
        return { path: file.path, sha: blob.sha };
      })
    );
    blobShas.push(...results);
  }

  // 5. Create a new tree with all files (no base_tree — full snapshot, so
  // deletions propagate). (F7b)
  const treeRes = await ghFetch(token, `/repos/${owner}/${sanitizedName}/git/trees`, {
    method: "POST",
    body: JSON.stringify({
      tree: blobShas.map(({ path, sha }) => ({
        path,
        mode: "100644",
        type: "blob",
        sha,
      })),
    }),
  });

  if (!treeRes.ok) {
    return NextResponse.json({ error: "Failed to create Git tree" }, { status: 500 });
  }
  const tree = await treeRes.json() as { sha: string };

  // 6. Create a commit
  const commitRes = await ghFetch(token, `/repos/${owner}/${sanitizedName}/git/commits`, {
    method: "POST",
    body: JSON.stringify({
      message: commitMessage,
      tree: tree.sha,
      ...(parentSha ? { parents: [parentSha] } : { parents: [] }),
    }),
  });

  if (!commitRes.ok) {
    return NextResponse.json({ error: "Failed to create commit" }, { status: 500 });
  }
  const commit = await commitRes.json() as { sha: string };

  // 7. Update (or create) the branch ref. This is the only step visible to the
  // outside world — if it fails, the commit exists but no branch points at it,
  // so we must surface the failure instead of falsely reporting success.
  let refRes2: Response;
  if (parentSha) {
    // Update existing ref
    refRes2 = await ghFetch(token, `/repos/${owner}/${sanitizedName}/git/refs/heads/${defaultBranch}`, {
      method: "PATCH",
      body: JSON.stringify({ sha: commit.sha, force: false }),
    });
  } else {
    // Create new ref (first commit on empty repo)
    refRes2 = await ghFetch(token, `/repos/${owner}/${sanitizedName}/git/refs`, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${defaultBranch}`, sha: commit.sha }),
    });
  }

  if (!refRes2.ok) {
    const err = (await refRes2.json().catch(() => ({}))) as { message?: string };
    // 422 (and sometimes 409) here means the remote branch advanced since we read
    // its HEAD — a non-fast-forward. The push did NOT land.
    const nonFastForward = refRes2.status === 422 || refRes2.status === 409;
    return NextResponse.json(
      {
        error: nonFastForward
          ? "Push rejected: the remote branch has new commits Gostera doesn't have (non-fast-forward). Pull/merge the remote changes, or re-create the repo, then push again."
          : `Failed to update branch ref: ${err.message ?? `HTTP ${refRes2.status}`}`,
      },
      { status: nonFastForward ? 409 : 500 }
    );
  }

  return NextResponse.json({
    success: true,
    repoUrl,
    repoName: sanitizedName,
    commitSha: commit.sha,
    filesCount: files.length,
  });
}
